/**:
  ros__parameters:
    path: system
    perception:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: perception
      analyzers:
        topic_status:
          type: 'diagnostic_aggregator/GenericAnalyzer'
          path: topic_status
          contains: [": perception_topic_status"]
          num_items: 0
